name: Build

on: [push, deployment]

jobs:
  build:
    runs-on: ubuntu-16.04
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - name: Create environment
      run: mkdir ${{runner.workspace}}/build
    - name: Run cmake
      working-directory: ${{runner.workspace}}/build
      run: cmake ${{github.workspace}}/headers
    - name: Run make
      working-directory: ${{runner.workspace}}/build
      run: make
    - name: Prepare autogen
      run: |
        mkdir output
        cp ${{github.workspace}}/src/lanteren.cpp autogen/lantern.cpp
        cp ${{github.workspace}}/include/lantern/lantern.h autogen/lantern.h
    - name: Run autogen
      working-directory: ${{runner.workspace}}/install
      run: ./lanterngen ${{github.workspace}}/headers/declarations/declarations.yaml ${{runner.workspace}}/output/lantern.cpp ${{runner.workspace}}/output/lantern.h
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: Autogen
        path: ${{runner.workspace}}/autogen
