name: Build

on: [push, deployment]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v2
    - name: cmake
      working-directory: ${{runner.workspace}}/build
      run: cmake ..
    - name: make
      if: runner.os != 'Windows'
      working-directory: ${{runner.workspace}}/build
      run: make
    - name: devenv
      if: runner.os == 'Windows'
      working-directory: ${{runner.workspace}}/build
      run: devenv /build Release CMake.sln
    - name: test
      run: ./build/lanterntest
