name: Build

on: [push, deployment]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v2
    - name: environment
      run: cmake -E make_directory ${{runner.workspace}}/build
    - name: cmake
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE
    - name: make
      if: runner.os != 'Windows'
      working-directory: ${{runner.workspace}}/build
      run: make
    - name: devenv
      if: runner.os == 'Windows'
      working-directory: ${{runner.workspace}}/build
      shell: cmd
      run: |
        "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\VsDevCmd.bat"
        devenv /build Release CMake.sln
    - name: test
      working-directory: ${{runner.workspace}}/build
      run: ./lanterntest
    - name: upload ubuntu
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v1
      with:
        name: lantern
        path: liblantern.so
    - name: upload osx
      if: runner.os == 'macOS'
      uses: actions/upload-artifact@v1
      with:
        name: lantern
        path: liblantern.dylib
    - name: upload windows
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v1
      with:
        name: lantern
        path: lantern.dll