name: Build

on: [push, deployment]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 3
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
        include:
          - os: windows-latest
            library: lantern.dll
            test: |
              & ./lanterntest.exe
            make: |
              & 'C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/Bin/MSBuild' lantern.sln /t:Build /p:Configuration=Release
            build: build/Release
          - os: ubuntu-latest
            library: liblantern.so
            test: ./lanterntest
            make: make
            build: build
          - os: macOS-latest
            library: liblantern.dylib
            test: ./lanterntest
            make: make
            build: build
    steps:
    - uses: actions/checkout@v2
    - name: Create environment
      run: cmake -E make_directory ${{runner.workspace}}/build
    - name: Run cmake
      working-directory: ${{runner.workspace}}/build
      run: cmake ${{github.workspace}}
    - name: Run make
      working-directory: ${{runner.workspace}}/build
      run: ${{matrix.make}}
    - name: Test library
      working-directory: ${{runner.workspace}}/${{matrix.build}}
      run: ${{matrix.test}} ${{matrix.library}}
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: ${{runner.os}}
        path: ${{runner.workspace}}/${{matrix.build}}/${{matrix.library}}
