name: Build

on: [push, deployment]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, ubuntu-16.04, macos-10.15]
        include:
          - os: windows-2019
            library: lantern.dll
            test: "& './lanterntest.exe' "
            make: "& 'C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/Bin/MSBuild' lantern.sln /t:Build /p:Configuration=Release"
            build: build/Release
            libext: .dll
            exeext: .exe
            fixlib:
            flavor: Release
            artifacts: lantern.dll
          - os: ubuntu-16.04
            library: liblantern.so
            test: ./lanterntest
            make: make
            build: build
            libext:
            exeext:
            fixlib: chrpath -r '$ORIGIN/.' liblantern.so 
            flavor: Release
            artifacts: liblantern.so
          - os: macos-10.15
            library: liblantern.dylib
            test: ./lanterntest
            make: make
            build: build
            libext: .dylib
            exeext:
            fixlib: install_name_tool -add_rpath @loader_path/. liblantern.dylib
            flavor: Release
            artifacts: liblantern.dylib
    steps:
    - uses: actions/checkout@v2
    - name: Create environment
      run: cmake -E make_directory ${{runner.workspace}}/build
    - name: Run cmake
      working-directory: ${{runner.workspace}}/build
      run: cmake -DCMAKE_BUILD_TYPE=${{matrix.flavor}} ${{github.workspace}}
    - name: Run make
      working-directory: ${{runner.workspace}}/build
      run: ${{matrix.make}}
    - name: Fix library
      working-directory: ${{runner.workspace}}/build
      run: ${{matrix.fixlib}}
    - name: Install libs
      working-directory: ${{runner.workspace}}
      run: |
        mkdir install
        cp ${{matrix.build}}/lanterntest${{matrix.exeext}} install/
        cp ${{matrix.build}}/${{matrix.library}} install/${{matrix.library}}
        cp build/libtorch/lib/*${{matrix.libext}} install
        mkdir artifacts
        cp -R ${{matrix.build}}/${{matrix.artifacts}} artifacts
        rm -r build
    - name: Test library
      working-directory: ${{runner.workspace}}/install
      run: ${{matrix.test}} ${{runner.workspace}}/install
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: ${{runner.os}}
        path: ${{runner.workspace}}/artifacts
  upload:
    needs: build
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        name: [macOS, Linux, Windows]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: ${{ matrix.name }}
      - name: Upload to lantern builds
        uses: actions-hub/gcloud@master
        env:
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          CLI: gsutil
        with:
          args: cp ${{ matrix.name }} gs://lantern-builds/${{ github.ref }}/${{ github.run_number }}/${{ matrix.names }}.zip
      - name: Upload to latest
        uses: actions-hub/gcloud@master
        env:
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          CLI: gsutil
        with:
          args: cp ${{ matrix.name }} gs://lantern-builds/${{ github.ref }}/latest/${{ matrix.names }}.zip
  autogen:
    runs-on: ubuntu-16.04
    name: autogen (ubuntu-16.04)
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - name: Create environment
      run: mkdir ${{runner.workspace}}/build
    - name: Run cmake
      working-directory: ${{runner.workspace}}/build
      run: cmake ${{github.workspace}}/headers
    - name: Run make
      working-directory: ${{runner.workspace}}/build
      run: make
    - name: Prepare autogen
      working-directory: ${{runner.workspace}}
      run: |
        mkdir output
        cp ${{github.workspace}}/src/lantern.cpp output/lantern.cpp
        cp ${{github.workspace}}/include/lantern/lantern.h output/lantern.h
    - name: Run autogen
      working-directory: ${{runner.workspace}}/build
      run: ./lanterngen ${{github.workspace}}/headers/declarations/declarations.yaml ${{runner.workspace}}/output/lantern.cpp ${{runner.workspace}}/output/lantern.h
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: Autogen
        path: ${{runner.workspace}}/output
