on:
  push:

name: Test on GPU
jobs:
  R-CMD-CHECK:
    name: GPU
    runs-on: self-hosted
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      INSTALL_TORCH: 1
      CRAN: https://demo.rstudiopm.com/all/__linux__/bionic/latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build -f docker/Dockerfile -t testtorch .
      - name: Run checks
        run: docker run --rm --gpus all testtorch sh torch/tools/check.sh
