on:
  push:
  pull_request:
  schedule:
    - cron: "0 1 * * *"

name: Test

jobs:
  R-CMD-check:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-16.04"]
        include:
          - os: ubuntu-16.04
            cran: https://demo.rstudiopm.com/all/__linux__/xenial/latest
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      CRAN: ${{ matrix.cran }}

    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master
      - name: Install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          Rscript -e "install.packages('remotes')" -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"
      - name: Install dependencies
        run: Rscript -e "install.packages('remotes')" -e "remotes::install_deps(dependencies = TRUE)" -e "remotes::install_cran('rcmdcheck')" -e "remotes::install_cran('devtools')"
      - name: Test
        run: Rscript -e "devtools::test()"
