# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  issue_comment:
    types: [created]

name: Commands

jobs:
  style:
    if: startsWith(github.event.comment.body, '/style')
    name: style
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/pr-fetch@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::roxygen2, any::styler
          needs: pr-document

      - name: Build lantern and get libtorch
        if: matrix.install == 0 || contains( github.event.pull_request.labels.*.name, 'lantern')
        run: |
          Rscript tools/buildlantern.R

      - name: Style and render documents
        if: success() && runner.os == 'Linux' && matrix.r_version == 'release' && startsWith(github.event.comment.body, '/style')
        run:  |
          set -x
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          sudo apt-get install -y clang-format perl || true
          time ./tools/style.sh || true
          find . -type f \( -name 'DESCRIPTION' -o -name "*.R" -o -name '*.h' -o -name '*.hpp' -o -name '*.c' -o -name '*.cc' -o -name '*.cpp' -o -name '*.cxx' \) \
            -not -path "./build/*" \
            -not -path "./check/*" \
            -not -path "./inst/include/*/*" \
            -not -path "./lantern/build/*" \
            -not -path "./lantern/headers/build/*" \
            -not -path "./revdep/*" \
            -not -path "*/gen-*.*" \
            -not -path "*/lantern.*" \
            -not -path "*/RcppExports.*" \
            -printf '%p\n' -exec git add {} \; || true
          git commit -m 'Styling and formatting R and C/C++ code' || echo 'No changes to commit'
          git add README.md NAMESPACE man/\* */RcppExports.\* || true
          git commit -m 'Roxygenize and render documents' || echo 'No changes to commit'
          git pull --ff-only || true
          git push origin || echo "No changes to commit"
        shell: bash

      - uses: r-lib/actions/pr-push@v2
        if: ${{ success() && runner.os == 'Linux' && matrix.r_version == 'release' && startsWith(github.event.comment.body, '/style') &&
                ( github.event_name == 'pull_request' || github.event.issue.pull_request ) &&
                ( github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER' ) }}
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
