on:
  issue_comment:
    types: [created]

name: Test on GPU
jobs:
  R-CMD-CHECK:
    if: startsWith(github.event.comment.body, '/gpu') && github.event.comment.user.login == 'dfalbel'
    name: GPU
    runs-on: self-hosted
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      INSTALL_TORCH: 1
      CRAN: https://demo.rstudiopm.com/all/__linux__/bionic/latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/pr-fetch@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master
      - name: Install dependencies
        run: Rscript -e "install.packages(c('remotes', 'rcmdcheck'))" -e "remotes::install_deps(dependencies = TRUE)"
      - name: Check
        run: rcmdcheck::rcmdcheck(args = c("--no-manual", "--no-multiarch"), error_on = "error", check_dir = "check")
        shell: Rscript {0}
      - name: Reveal testthat details
        run: find . -name testthat.Rout -exec cat '{}' ';'
      - name: Cleanup machine
        if: always()
        run: |
          cd ../..
          rm -r torch
